// generated by SMACK version 2.4.1 for corral
// via /usr/local/bin/smack -q -t --no-memory-splitting --bit-precise --clang-options=-DCUSTOM_VERIFIER_ASSERT -O3 -fno-vectorize -fno-slp-vectorize -I./include/ -bpl ./output/aiob_1-O3.bpl /Users/ponce/git/Dat3M/./output/aiob_1_tmp.c

procedure {:entrypoint} main()
  returns ($r: bv32)
{
  var $i4: int;
$bb0:
  $i4 := 4;
  call __VERIFIER_atomic_end();
  $exn := false;
  return;
}
