/*
  MIT License
  Copyright (c) 2023 邱维东
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 */

lexer grammar LLVMIRLexer;

tokens { DataLayoutQuote }

KW_SourceFilename: 'source_filename';
Equal: '=';
KW_Target: 'target';
Minus: '-';
Colon: ':';
KW_Triple: 'triple';
KW_Module: 'module';
KW_Asm: 'asm';
KW_Type: 'type';
KW_Comdat: 'comdat';
KW_Any: 'any';
KW_Exactmatch: 'exactmatch';
KW_Largest: 'largest';
KW_Nodeduplicate: 'nodeduplicate';
KW_Samesize: 'samesize';
Comma: ',';
KW_Alias: 'alias';
KW_Ifunc: 'ifunc';
KW_Declare: 'declare';
KW_Define: 'define';
KW_Attributes: 'attributes';
LBrace: '{';
RBrace: '}';
Bang: '!';
KW_Uselistorder: 'uselistorder';
KW_UselistorderBb: 'uselistorder_bb';
LParen: '(';
RParen: ')';
KW_Cc: 'cc';
KW_Gc: 'gc';
KW_Prefix: 'prefix';
KW_Prologue: 'prologue';
KW_Personality: 'personality';
KW_Ret: 'ret';
KW_Void: 'void';
KW_Br: 'br';
KW_Switch: 'switch';
LBracket: '[';
RBracket: ']';
KW_Indirectbr: 'indirectbr';
KW_Resume: 'resume';
KW_Catchret: 'catchret';
KW_From: 'from';
KW_To: 'to';
KW_Cleanupret: 'cleanupret';
KW_Unwind: 'unwind';
KW_Unreachable: 'unreachable';
KW_Invoke: 'invoke';
KW_Callbr: 'callbr';
KW_Catchswitch: 'catchswitch';
KW_Within: 'within';
KW_Label: 'label';
KW_Caller: 'caller';
KW_DIExpression: '!DIExpression';
KW_NoSanitizeAddress: 'no_sanitize_address';
KW_NoSanitizeHwaddress: 'no_sanitize_hwaddress';
KW_SanitizeAddressDyninit: 'sanitize_address_dyninit';
KW_SanitizeMemtag: 'sanitize_memtag';
KW_Section: 'section';
KW_Partition: 'partition';
KW_True: 'true';
KW_False: 'false';
KW_Null: 'null';
KW_None: 'none';
Less: '<';
Greater: '>';
KW_C: 'c';
KW_Zeroinitializer: 'zeroinitializer';
KW_Undef: 'undef';
KW_Poison: 'poison';
KW_Blockaddress: 'blockaddress';
KW_DsoLocalEquivalent: 'dso_local_equivalent';
KW_NoCfi: 'no_cfi';
KW_DIArgList: '!DIArgList';
KW_Sideeffect: 'sideeffect';
KW_Alignstack: 'alignstack';
KW_Inteldialect: 'inteldialect';
KW_Opaque: 'opaque';
Star: '*';
Ellipsis: '...';
KW_Align: 'align';
KW_Allockind: 'allockind';
KW_Allocsize: 'allocsize';
KW_Uwtable: 'uwtable';
KW_Async: 'async';
KW_Sync: 'sync';
KW_VscaleRange: 'vscale_range';
KW_Byref: 'byref';
KW_Byval: 'byval';
KW_Dereferenceable: 'dereferenceable';
KW_DereferenceableOrNull: 'dereferenceable_or_null';
KW_Elementtype: 'elementtype';
KW_Inalloca: 'inalloca';
KW_Allocalign: 'allocalign';
KW_Allocptr: 'allocptr';
KW_Immarg: 'immarg';
KW_Inreg: 'inreg';
KW_Nest: 'nest';
KW_Noalias: 'noalias';
KW_Nocapture: 'nocapture';
KW_Nofree: 'nofree';
KW_Nonnull: 'nonnull';
KW_Noundef: 'noundef';
KW_Readnone: 'readnone';
KW_Readonly: 'readonly';
KW_Returned: 'returned';
KW_Signext: 'signext';
KW_Swiftasync: 'swiftasync';
KW_Swifterror: 'swifterror';
KW_Swiftself: 'swiftself';
KW_Writeonly: 'writeonly';
KW_Zeroext: 'zeroext';
KW_Preallocated: 'preallocated';
KW_Captures: 'captures';
KW_Address: 'address';
KW_AddressIsNull: 'address_is_null';
KW_Provenance: 'provenance';
KW_ReadProvenance: 'read_provenance';
KW_Initializes: 'initializes';
KW_Range: 'range';
KW_Sret: 'sret';
KW_X: 'x';
KW_Vscale: 'vscale';
KW_X86Mmx: 'x86_mmx';
KW_Token: 'token';
KW_Ptr: 'ptr';
KW_Addrspace: 'addrspace';
KW_ThreadLocal: 'thread_local';
KW_Metadata: 'metadata';
KW_Bitcast: 'bitcast';
KW_Getelementptr: 'getelementptr';
KW_Inrange: 'inrange';
KW_Addrspacecast: 'addrspacecast';
KW_Inttoptr: 'inttoptr';
KW_Icmp: 'icmp';
KW_Fcmp: 'fcmp';
KW_Select: 'select';
KW_Trunc: 'trunc';
KW_Zext: 'zext';
KW_Sext: 'sext';
KW_Fptrunc: 'fptrunc';
KW_Fpext: 'fpext';
KW_Fptoui: 'fptoui';
KW_Fptosi: 'fptosi';
KW_Uitofp: 'uitofp';
KW_Sitofp: 'sitofp';
KW_Ptrtoint: 'ptrtoint';
KW_Extractelement: 'extractelement';
KW_Insertelement: 'insertelement';
KW_Shufflevector: 'shufflevector';
KW_Shl: 'shl';
KW_Lshr: 'lshr';
KW_Exact: 'exact';
KW_Ashr: 'ashr';
KW_And: 'and';
KW_Or: 'or';
KW_Xor: 'xor';
KW_Add: 'add';
KW_Sub: 'sub';
KW_Mul: 'mul';
KW_Fneg: 'fneg';
KW_Store: 'store';
KW_Volatile: 'volatile';
KW_Atomic: 'atomic';
KW_Syncscope: 'syncscope';
KW_Fence: 'fence';
KW_Fadd: 'fadd';
KW_Fsub: 'fsub';
KW_Fmul: 'fmul';
KW_Udiv: 'udiv';
KW_Sdiv: 'sdiv';
KW_Fdiv: 'fdiv';
KW_Urem: 'urem';
KW_Srem: 'srem';
KW_Frem: 'frem';
KW_Disjoint: 'disjoint';
KW_Extractvalue: 'extractvalue';
KW_Insertvalue: 'insertvalue';
KW_Alloca: 'alloca';
KW_Load: 'load';
KW_Cmpxchg: 'cmpxchg';
KW_Weak: 'weak';
KW_Atomicrmw: 'atomicrmw';
KW_Nneg: 'nneg';
KW_Samesign: 'samesign';
KW_Phi: 'phi';
KW_Freeze: 'freeze';
KW_Musttail: 'musttail';
KW_Notail: 'notail';
KW_Tail: 'tail';
KW_Call: 'call';
KW_VaArg: 'va_arg';
KW_Landingpad: 'landingpad';
KW_Cleanup: 'cleanup';
KW_Catchpad: 'catchpad';
KW_Cleanuppad: 'cleanuppad';
KW_Catch: 'catch';
KW_Filter: 'filter';
KW_ExternWeak: 'extern_weak';
KW_External: 'external';
KW_Appending: 'appending';
KW_AvailableExternally: 'available_externally';
KW_Common: 'common';
KW_Internal: 'internal';
KW_Linkonce: 'linkonce';
KW_LinkonceOdr: 'linkonce_odr';
KW_Private: 'private';
KW_WeakOdr: 'weak_odr';
KW_DsoLocal: 'dso_local';
KW_DsoPreemptable: 'dso_preemptable';
KW_Default: 'default';
KW_Hidden: 'hidden';
KW_Protected: 'protected';
KW_Dllexport: 'dllexport';
KW_Dllimport: 'dllimport';
KW_Initialexec: 'initialexec';
KW_Localdynamic: 'localdynamic';
KW_Localexec: 'localexec';
KW_LocalUnnamedAddr: 'local_unnamed_addr';
KW_UnnamedAddr: 'unnamed_addr';
KW_ExternallyInitialized: 'externally_initialized';
KW_Constant: 'constant';
KW_Global: 'global';
KW_Alwaysinline: 'alwaysinline';
KW_Argmemonly: 'argmemonly';
KW_Builtin: 'builtin';
KW_Cold: 'cold';
KW_Convergent: 'convergent';
KW_DisableSanitizerInstrumentation: 'disable_sanitizer_instrumentation';
KW_FnRetThunkExtern: 'fn_ret_thunk_extern';
KW_Hot: 'hot';
KW_InaccessiblememOrArgmemonly: 'inaccessiblemem_or_argmemonly';
KW_Inaccessiblememonly: 'inaccessiblememonly';
KW_Inlinehint: 'inlinehint';
KW_Jumptable: 'jumptable';
KW_Minsize: 'minsize';
KW_Mustprogress: 'mustprogress';
KW_Naked: 'naked';
KW_Nobuiltin: 'nobuiltin';
KW_Nocallback: 'nocallback';
KW_NocfCheck: 'nocf_check';
KW_Nocreateundeforpoison: 'nocreateundeforpoison';
KW_Noduplicate: 'noduplicate';
KW_Noimplicitfloat: 'noimplicitfloat';
KW_Noinline: 'noinline';
KW_Nomerge: 'nomerge';
KW_Nonlazybind: 'nonlazybind';
KW_Noprofile: 'noprofile';
KW_Norecurse: 'norecurse';
KW_Noredzone: 'noredzone';
KW_Noreturn: 'noreturn';
KW_NosanitizeBounds: 'nosanitize_bounds';
KW_NosanitizeCoverage: 'nosanitize_coverage';
KW_Nosync: 'nosync';
KW_Nounwind: 'nounwind';
KW_NullPointerIsValid: 'null_pointer_is_valid';
KW_Optforfuzzing: 'optforfuzzing';
KW_Optnone: 'optnone';
KW_Optsize: 'optsize';
KW_Presplitcoroutine: 'presplitcoroutine';
KW_ReturnsTwice: 'returns_twice';
KW_Safestack: 'safestack';
KW_SanitizeAddress: 'sanitize_address';
KW_SanitizeHwaddress: 'sanitize_hwaddress';
KW_SanitizeMemory: 'sanitize_memory';
KW_SanitizeThread: 'sanitize_thread';
KW_Shadowcallstack: 'shadowcallstack';
KW_Speculatable: 'speculatable';
KW_SpeculativeLoadHardening: 'speculative_load_hardening';
KW_Ssp: 'ssp';
KW_Sspreq: 'sspreq';
KW_Sspstrong: 'sspstrong';
KW_Strictfp: 'strictfp';
KW_Willreturn: 'willreturn';
KW_Memory: 'memory(';
KW_ArgmemField: 'argmem:';
KW_InaccessiblememField: 'inaccessiblemem:';
KW_Readwrite: 'readwrite';
KW_Read: 'read';
KW_Write: 'write';
KW_Distinct: 'distinct';
KW_Inbounds: 'inbounds';
KW_Nsw: 'nsw';
KW_Nuw: 'nuw';
KW_Eq: 'eq';
KW_Ne: 'ne';
KW_Sge: 'sge';
KW_Sgt: 'sgt';
KW_Sle: 'sle';
KW_Slt: 'slt';
KW_Uge: 'uge';
KW_Ugt: 'ugt';
KW_Ule: 'ule';
KW_Ult: 'ult';
KW_Oeq: 'oeq';
KW_Oge: 'oge';
KW_Ogt: 'ogt';
KW_Ole: 'ole';
KW_Olt: 'olt';
KW_One: 'one';
KW_Ord: 'ord';
KW_Ueq: 'ueq';
KW_Une: 'une';
KW_Uno: 'uno';
KW_AcqRel: 'acq_rel';
KW_Acquire: 'acquire';
KW_Monotonic: 'monotonic';
KW_Release: 'release';
KW_SeqCst: 'seq_cst';
KW_Unordered: 'unordered';
KW_Aarch64SveVectorPcs: 'aarch64_sve_vector_pcs';
KW_Aarch64VectorPcs: 'aarch64_vector_pcs';
KW_AmdgpuCs: 'amdgpu_cs';
KW_AmdgpuEs: 'amdgpu_es';
KW_AmdgpuGfx: 'amdgpu_gfx';
KW_AmdgpuGs: 'amdgpu_gs';
KW_AmdgpuHs: 'amdgpu_hs';
KW_AmdgpuKernel: 'amdgpu_kernel';
KW_AmdgpuLs: 'amdgpu_ls';
KW_AmdgpuPs: 'amdgpu_ps';
KW_AmdgpuVs: 'amdgpu_vs';
KW_Anyregcc: 'anyregcc';
KW_ArmAapcsVfpcc: 'arm_aapcs_vfpcc';
KW_ArmAapcscc: 'arm_aapcscc';
KW_ArmApcscc: 'arm_apcscc';
KW_AvrIntrcc: 'avr_intrcc';
KW_AvrSignalcc: 'avr_signalcc';
KW_Ccc: 'ccc';
KW_CfguardCheckcc: 'cfguard_checkcc';
KW_Coldcc: 'coldcc';
KW_CxxFastTlscc: 'cxx_fast_tlscc';
KW_Fastcc: 'fastcc';
KW_Ghccc: 'ghccc';
KW_HhvmCcc: 'hhvm_ccc';
KW_Hhvmcc: 'hhvmcc';
KW_IntelOclBicc: 'intel_ocl_bicc';
KW_Msp430Intrcc: 'msp430_intrcc';
KW_PreserveAllcc: 'preserve_allcc';
KW_PreserveMostcc: 'preserve_mostcc';
KW_PtxDevice: 'ptx_device';
KW_PtxKernel: 'ptx_kernel';
KW_SpirFunc: 'spir_func';
KW_SpirKernel: 'spir_kernel';
KW_Swiftcc: 'swiftcc';
KW_Swifttailcc: 'swifttailcc';
KW_Tailcc: 'tailcc';
KW_WebkitJscc: 'webkit_jscc';
KW_Win64cc: 'win64cc';
KW_X8664Sysvcc: 'x86_64_sysvcc';
KW_X86Fastcallcc: 'x86_fastcallcc';
KW_X86Intrcc: 'x86_intrcc';
KW_X86Regcallcc: 'x86_regcallcc';
KW_X86Stdcallcc: 'x86_stdcallcc';
KW_X86Thiscallcc: 'x86_thiscallcc';
KW_X86Vectorcallcc: 'x86_vectorcallcc';
KW_Afn: 'afn';
KW_Arcp: 'arcp';
KW_Contract: 'contract';
KW_Fast: 'fast';
KW_Ninf: 'ninf';
KW_Nnan: 'nnan';
KW_Nsz: 'nsz';
KW_Reassoc: 'reassoc';
KW_Fmax: 'fmax';
KW_Fmin: 'fmin';
KW_Max: 'max';
KW_Min: 'min';
KW_Nand: 'nand';
KW_Umax: 'umax';
KW_Umin: 'umin';
KW_Xchg: 'xchg';
KW_Half: 'half';
KW_Bfloat: 'bfloat';
KW_Float: 'float';
KW_Double: 'double';
KW_X86Fp80: 'x86_fp80';
KW_Fp128: 'fp128';
KW_PpcFp128: 'ppc_fp128';
KW_DIAssignID: '!DIAssignID()';
KW_DIBasicType: '!DIBasicType';
KW_DICommonBlock: '!DICommonBlock';
KW_DICompileUnit: '!DICompileUnit';
KW_DICompositeType: '!DICompositeType';
KW_DIDerivedType: '!DIDerivedType';
KW_DIEnumerator: '!DIEnumerator';
KW_DIFile: '!DIFile';
KW_DIGlobalVariable: '!DIGlobalVariable';
KW_DIGlobalVariableExpression: '!DIGlobalVariableExpression';
KW_DIImportedEntity: '!DIImportedEntity';
KW_DILabel: '!DILabel';
KW_DILexicalBlock: '!DILexicalBlock';
KW_DILexicalBlockFile: '!DILexicalBlockFile';
KW_DILocalVariable: '!DILocalVariable';
KW_DILocation: '!DILocation';
KW_DIMacro: '!DIMacro';
KW_DIMacroFile: '!DIMacroFile';
KW_DIModule: '!DIModule';
KW_DINamespace: '!DINamespace';
KW_DIObjCProperty: '!DIObjCProperty';
KW_DIStringType: '!DIStringType';
KW_DISubprogram: '!DISubprogram';
KW_DISubrange: '!DISubrange';
KW_DISubroutineType: '!DISubroutineType';
KW_DITemplateTypeParameter: '!DITemplateTypeParameter';
KW_DITemplateValueParameter: '!DITemplateValueParameter';
KW_GenericDINode: '!GenericDINode';
KW_TagField: 'tag:';
KW_HeaderField: 'header:';
KW_OperandsField: 'operands:';
KW_NameField: 'name:';
KW_TypeField: 'type:';
KW_DefaultedField: 'defaulted:';
KW_ValueField: 'value:';
KW_FlagsField: 'flags:';
Pipe: '|';
KW_CcField: 'cc:';
KW_AlignField: 'align:';
KW_AllocatedField: 'allocated:';
KW_AnnotationsField: 'annotations:';
KW_ArgField: 'arg:';
KW_AssociatedField: 'associated:';
KW_AttributesField: 'attributes:';
KW_BaseTypeField: 'baseType:';
KW_ChecksumField: 'checksum:';
KW_ChecksumkindField: 'checksumkind:';
KW_ColumnField: 'column:';
KW_ConfigMacrosField: 'configMacros:';
KW_ContainingTypeField: 'containingType:';
KW_CountField: 'count:';
KW_DebugInfoForProfilingField: 'debugInfoForProfiling:';
KW_DeclarationField: 'declaration:';
KW_DirectoryField: 'directory:';
KW_DiscriminatorField: 'discriminator:';
KW_DataLocationField: 'dataLocation:';
KW_DwarfAddressSpaceField: 'dwarfAddressSpace:';
KW_DwoIdField: 'dwoId:';
KW_ElementsField: 'elements:';
KW_EmissionKindField: 'emissionKind:';
KW_DebugDirectivesOnly: 'DebugDirectivesOnly';
KW_FullDebug: 'FullDebug';
KW_LineTablesOnly: 'LineTablesOnly';
KW_NoDebug: 'NoDebug';
KW_EncodingField: 'encoding:';
KW_EntityField: 'entity:';
KW_EnumsField: 'enums:';
KW_ExportSymbolsField: 'exportSymbols:';
KW_ExprField: 'expr:';
KW_ExtraDataField: 'extraData:';
KW_FileField: 'file:';
KW_FilenameField: 'filename:';
KW_GetterField: 'getter:';
KW_GlobalsField: 'globals:';
KW_IdentifierField: 'identifier:';
KW_ImportsField: 'imports:';
KW_IncludePathField: 'includePath:';
KW_InlinedAtField: 'inlinedAt:';
KW_IsDeclField: 'isDecl:';
KW_IsDefinitionField: 'isDefinition:';
KW_IsImplicitCodeField: 'isImplicitCode:';
KW_IsLocalField: 'isLocal:';
KW_IsOptimizedField: 'isOptimized:';
KW_IsUnsignedField: 'isUnsigned:';
KW_ApinotesField: 'apinotes:';
KW_LanguageField: 'language:';
KW_LineField: 'line:';
KW_LinkageNameField: 'linkageName:';
KW_LowerBoundField: 'lowerBound:';
KW_MacrosField: 'macros:';
KW_NameTableKindField: 'nameTableKind:';
KW_Apple: 'Apple';
KW_GNU: 'GNU';
KW_None2: 'None';
KW_Default2: 'Default';
KW_NodesField: 'nodes:';
KW_OffsetField: 'offset:';
KW_ProducerField: 'producer:';
KW_RangesBaseAddressField: 'rangesBaseAddress:';
KW_RankField: 'rank:';
KW_RetainedNodesField: 'retainedNodes:';
KW_RetainedTypesField: 'retainedTypes:';
KW_RuntimeLangField: 'runtimeLang:';
KW_RuntimeVersionField: 'runtimeVersion:';
KW_ScopeField: 'scope:';
KW_ScopeLineField: 'scopeLine:';
KW_SdkField: 'sdk:';
KW_SetterField: 'setter:';
KW_SizeField: 'size:';
KW_SourceField: 'source:';
KW_SpFlagsField: 'spFlags:';
KW_SplitDebugFilenameField: 'splitDebugFilename:';
KW_SplitDebugInliningField: 'splitDebugInlining:';
KW_StrideField: 'stride:';
KW_StringLengthField: 'stringLength:';
KW_StringLengthExpressionField: 'stringLengthExpression:';
KW_StringLocationExpressionField: 'stringLocationExpression:';
KW_SysrootField: 'sysroot:';
KW_TargetFuncNameField: 'targetFuncName:';
KW_TemplateParamsField: 'templateParams:';
KW_ThisAdjustmentField: 'thisAdjustment:';
KW_ThrownTypesField: 'thrownTypes:';
KW_TypesField: 'types:';
KW_UnitField: 'unit:';
KW_UpperBoundField: 'upperBound:';
KW_VarField: 'var:';
KW_VirtualIndexField: 'virtualIndex:';
KW_VirtualityField: 'virtuality:';
KW_VtableHolderField: 'vtableHolder:';

DataLayoutStart: 'datalayout' -> pushMode(DataLayoutHeader);

fragment AsciiLetter: [A-Za-z];
fragment Letter: AsciiLetter | [-$._];
fragment EscapeLetter: Letter | '\\';
fragment DecimalDigit: [0-9];
fragment HexDigit: [A-Fa-f] | DecimalDigit;
fragment Decimals: DecimalDigit+;
fragment Name: Letter (Letter | DecimalDigit)*;
fragment EscapeName:
	EscapeLetter (EscapeLetter | DecimalDigit)*;
fragment Id: Decimals;
fragment IntHexLit: [us] '0x' HexDigit+;
// 浮点型常量
fragment Sign: [+-];
fragment FracLit: Sign? Decimals '.' DecimalDigit*;
fragment SciLit: FracLit [eE] Sign? Decimals;
/*
 HexFPConstant 0x{_hex_digit}+ // 16 hex digits
 HexFP80Constant 0xK{_hex_digit}+ // 20 hex digits
 HexFP128Constant 0xL{_hex_digit}+ // 32 hex digits
 HexPPC128Constant 0xM{_hex_digit}+ // 32 hex
 digits
 HexHalfConstant 0xH{_hex_digit}+ // 4 hex digits
 HexBFloatConstant 0xR{_hex_digit}+ // 4
 hex digits
 */
fragment FloatHexLit: '0x' [KLMHR]? HexDigit+;
fragment GlobalName: '@' (Name | QuotedString);
fragment GlobalId: '@' Id;
fragment LocalName: '%' (Name | QuotedString);
fragment LocalId: '%' Id;
fragment QuotedString: '"' (~["\r\n])* '"';

Comment: ';' .*? '\r'? '\n' -> channel(HIDDEN);
WhiteSpace: [ \t\n\r]+ -> skip;
IntLit: ('-'? DecimalDigit+ | IntHexLit);
FloatLit: FracLit | SciLit | FloatHexLit;
StringLit: QuotedString;
GlobalIdent: GlobalName | GlobalId;
LocalIdent: LocalName | LocalId;
LabelIdent: ((Letter | DecimalDigit)+ ':' | QuotedString ':');
AttrGroupId: '#' Id;
DebugRecord: '#dbg_' Name;
ComdatName: '$' (Name | QuotedString);
MetadataName: '!' EscapeName;
MetadataId: '!' Id;
IntType: 'i' DecimalDigit+;
DwarfTag: 'DW_TAG_' (AsciiLetter | DecimalDigit | '_')*;
DwarfAttEncoding: 'DW_ATE_' (AsciiLetter | DecimalDigit | '_')*;
DiFlag: 'DIFlag' (AsciiLetter | DecimalDigit | '_')*;
DispFlag: 'DISPFlag' (AsciiLetter | DecimalDigit | '_')*;
DwarfLang: 'DW_LANG_' (AsciiLetter | DecimalDigit | '_')*;
DwarfCc: 'DW_CC_' (AsciiLetter | DecimalDigit | '_')*;
ChecksumKind: 'CSK_' (AsciiLetter | DecimalDigit | '_')*;
DwarfVirtuality:
	'DW_VIRTUALITY_' (AsciiLetter | DecimalDigit | '_')*;
DwarfMacinfo: 'DW_MACINFO_' (AsciiLetter | DecimalDigit | '_')*;
DwarfOp: 'DW_OP_' (AsciiLetter | DecimalDigit | '_')*;

mode DataLayoutHeader;

DataLayoutHeaderEqual: '=' -> type(Equal);
DataLayoutOpenQuote: '"' -> type(DataLayoutQuote), mode(DataLayoutContents);
DataLayoutHeaderWhiteSpace: [ \t\n\r]+ -> skip;
DataLayoutHeaderComment: ';' .*? '\r'? '\n' -> channel(HIDDEN);

mode DataLayoutContents;

DataLayoutCloseQuote: '"' -> type(DataLayoutQuote), popMode;
DataLayoutDash: '-' -> type(Minus);
DataLayoutColon: ':' -> type(Colon);
DataLayoutLittleEndian: 'e';
DataLayoutBigEndian: 'E';
DataLayoutPointer: 'p';
DataLayoutInteger: 'i';
DataLayoutFloat: 'f';
DataLayoutAggregate: 'a';
DataLayoutInt: DecimalDigit+;
// Layout entries not used by Dartagnan, such as mangling and native integer widths.
DataLayoutIgnoredSpecification: ~[pifaEe0-9:" \t\r\n-] ~[" \t\r\n-]*;
