# Compilation pipeline for SV-COMP properties without sanitizer instrumentation.
workdir: "$DAT3M_OUTPUT"

pipelines:
  - pipeline: ".c"
    aliases: [".i"]
    output: "{basename}.ll"
    commands:
      - name: "Compile"
        tool: "clang"
        input: "{pipeline_input}"
        output: "{basename}.ll"
        args: ["-I", "$DAT3M_HOME/include", "-fgnu89-inline", "-Xclang", "-disable-O0-optnone", "-S", "-emit-llvm", "-g", "-gcolumn-info", "{cmd_input}", "-o", "{cmd_output}"]
